os: linux
dist: jammy

jobs:
  include:
    - name: "job one"
      vm: 
        create:
          name: 23june_03
      script: 
        - echo "condition with job test"
        - echo $TRAVIS_COMMIT_MESSAGE
        - sleep 50
